AWSTemplateFormatVersion: "2010-09-09"
Description: Data Quest - Secrets (BLS user-agent, contact info)

Parameters:
  Env:
    Type: String
    Default: dev
  ContactEmail:
    Type: String
    Default: "devjayengineer@gmail.com"
  ContactPhone:
    Type: String
    Default: "+1-555-555-5555"

Resources:
  DQConfigSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub dq-config-${Env}
      Description: Config for Data Quest (BLS user-agent, contact info)
      SecretString: !Sub |
        {
          "blsUserAgent": "DataQuest-${Env} (Email: ${ContactEmail}; Phone: ${ContactPhone})"
        }

Outputs:
  DQConfigSecretArn:
    Value: !Ref DQConfigSecret
    Export:
      Name: !Sub dq-config-secret-arn-${Env}
